### ISSUE TITLE
Missing attachments after legacy migration

### ISSUE THREAD

**Issue by Pyromane** [Part-DB/Part-DB-server#272]
The migration was successful without any error messages, but I am missing a lot of attachments.

This is already visible in the statistics:
**Legacy Version: 0.5.15 (stable)**
Number of attachments: 1533

**Version: 1.3.0-dev (master/e0e5fb3)**
Number of all file attachments 765
Number of all attachments uploaded by the user 603

The following entries can be read in the event log in PartD-DB:
![eventlog](https://user-images.githubusercontent.com/5962901/232250593-d1578b22-d892-4ccc-b04d-e905e9058e7a.png)

While investigating the cause, I came across the following in the attachments table:
![db](https://user-images.githubusercontent.com/5962901/232250598-73baa043-5849-47be-8fca-92fbe3d25896.png)
For the part with ID 334, the two images are displayed cleanly, but for item 335, neither the image nor the two PDFs are displayed.
Is this possibly related to the different "class_name"?

**Comment by jbtronics** [comment]
Strange... I will look into it

**Comment by jbtronics** [comment]
It was actually related to the wrong class_name. My own database missed a few attachments too, but never noticed it. So thanks for reporting.

With the newest commit there is a new database migration (run `php bin/console doctrine:migrations:migrate`), which fixes the class_name to the new format. Then the attachments should show up.

If you have deleted some parts since the migration to the Part-DB 1.0 version, and they had attachments associated, which had not shown up, they will be deleted too. (to prevent issues with database integrity)
