### ISSUE TITLE
Image attachment 

### ISSUE THREAD

**Issue by pdo59** [Part-DB/Part-DB-server#328]
There is a problem with inserting Attachments to categories and to footprints.
I modified a first category by adding an external image to use as a thumbnail image, all ok.
Then I repeated the operation with a second category, after saving it, the system produced the Error 500.
I cleared the cache, reset the permissions but the error still persists, so I edited the two categories via SQL and set the "id_preview_attachment" field to NULL and the system works.
The same thing happened with the footprint table, and I used the same method, setting the "id_preview_attachment" field to NULL, to get a working system.

**Server Side**
- Part-DB Version: 1.6.0-dev (master/)
- PHP Version: 8.1.21 (SAPI: apache2handler)
- Database Server 10.5.19-MariaDB-0+deb11u2

**Desktop (please complete the following information):**
 - OS: MacOs or Debian11
 - Browser Safari 16.5.2 - Firefox 102.13.0esr (64-bit)

**Comment by jbtronics** [comment]
That should be fixed in the latest master commit.

For some reason, the way the entries of the element selectors are cached, started to make problems with the preview images (after it worked flawless for years)... I rewrote the caching part, so that the elements are refreshed from DB, and now it works properly again.
