### ISSUE TITLE
View and search settings reset to defaults after some time

### ISSUE THREAD

**Issue by interconnect80** [Part-DB/Part-DB-server#424]
**Describe the bug**
View and search settings reset after some time.  When viewing all parts in a category, for example, and you choose certain column headers (like MPN, tags, Created at, etc.) when you come back some time later, those customizations have reset to the defaults.  Same happen with "search options"; customizing search options is not saved and some time later they reset to the defaults.  Would be very helpful to have those settings stay permanent until otherwise changed by the user.

**To Reproduce**
1. Go to Categories and choose a category to view all parts within that category, or go to Show -> Show All Parts.  Also applies to custom search options.
2. Click gear icon to add or remove column headers.
3. Drag them around to customize the view (not required).
4. Some time later, all these customizations are lost and are reset to default.  Will reset in even just a matter of hours.  I do not know why this happens.

**Expected behavior**
To not have any customizations lost until the user changes them or purposefully resets them to default.

**Server Side**
- Part-DB Version:  1.8.2

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser:  Chrome
 - Version:  118.0

**Comment by influx3k** [comment]
Are there any plans to fix this?

**Comment by virtadpt** [comment]
See also #64.

**Comment by influx3k** [comment]
Ok, I read that. Same request, however there must still be an issue because the settings reset on the same machine and same browser after some period of time. Sometimes after an hour or two.

**Comment by jbtronics** [comment]
The table columns get saved for each type of table to your browsers localStorage. It is only available to the device and browser where you changed the settings, but the settings should be saved indefinitely. If the settings get lost after a short time, you should check your browser settings and plugins. Depending on your browser clearing the history and/or browser cache, could also delete the localStorage and therefore Part-DB settings on the table columns. Part-DB can not control what your browser does with the data.

For the search settings, they were not saved at all. They just persistet, as long as the page was not reloaded. With the latest commit, which will be part of Part-DB 1.9, the search settings, get saved to the localStorage too, and therefore should be a lot more persistent.

Regarding storing this info in a place other than localStorage, there is already issue #64, therefore I will close this issue here.

If you want to permanently configure the part table column, there is the `TABLE_PARTS_DEFAULT_COLUMNS` env, which allows you to configure these globally (The users can still customize it for themselves): https://docs.part-db.de/configuration.html#table-related-settings

**Comment by virtadpt** [comment]
I didn't know about `TABLE_PARTS_DEFAULT_COLUMNS` - thanks!

**Comment by influx3k** [comment]
> The table columns get saved for each type of table to your browsers localStorage. It is only available to the device and browser where you changed the settings, but the settings should be saved indefinitely. If the settings get lost after a short time, you should check your browser settings and plugins. Depending on your browser clearing the history and/or browser cache, could also delete the localStorage and therefore Part-DB settings on the table columns. Part-DB can not control what your browser does with the data.
> 
> For the search settings, they were not saved at all. They just persistet, as long as the page was not reloaded. With the latest commit, which will be part of Part-DB 1.9, the search settings, get saved to the localStorage too, and therefore should be a lot more persistent.
> 
> Regarding storing this info in a place other than localStorage, there is already issue #64, therefore I will close this issue here.
> 
> If you want to permanently configure the part table column, there is the `TABLE_PARTS_DEFAULT_COLUMNS` env, which allows you to configure these globally (The users can still customize it for themselves): https://docs.part-db.de/configuration.html#table-related-settings

Thanks for the info, however I tried this and it did not work.  I made an ENV variable and put the following:
name:  TABLE_PARTS_DEFAULT_COLUMNS
value:  name,manufacturer,storage_location,manufacturer_product_number,tags,description,lastModified

No deal; I do not get those columns when viewing a part table.  For example, when viewing an entire category, I do not get the default set of columns I set in the ENV variable.

**Comment by jbtronics** [comment]
Have you cleared the cache after changing the env setting?

**Comment by influx3k** [comment]
> Have you cleared the cache after changing the env setting?

Yes, I did, but now appears to maybe be working correctly.  I will keep my eye on it.  I cleared the cache, but not cookies.  Is it stored as a cookie or actually in the cache?

**Comment by jbtronics** [comment]
> Is it stored as a cookie or actually in the cache?

Neither. In localStorage. How you can clear it will depend on your browser. But I would suspect, that it will be cleared together with the cookies, as they are of similar persistance.

**Comment by influx3k** [comment]
> > Is it stored as a cookie or actually in the cache?
> 
> Neither. In localStorage. How you can clear it will depend on your browser. But I would suspect, that it will be cleared together with the cookies, as they are of similar persistance.

Using Google Chrome.  I had just cleared cached images and files; all time.
