### ISSUE TITLE
request for Chinese language

### ISSUE THREAD

**Issue by rahxphoon** [Part-DB/Part-DB-server#500]
I wish there is a Chinese language version to choose
how can I contribute with it, thanks

**Comment by jbtronics** [comment]
There was already a chinese translation started: https://part-db.crowdin.com/part-db/zh-CN

The translated strings are already part of Part-DB (you can see it, if you use a `/zh/` prefix for path instead of a `/en/` one), however as they are many missing ones, so it is not feautured in the language selector yet. 

You can use the crowdin platform linked above, to contribute to the translations. See 
this guide, on how to contribute to translations: https://github.com/Part-DB/Part-DB-server/discussions/468
