### ISSUE TITLE
Search & Search options windows are not hidden when losing focus

### ISSUE THREAD

**Issue by NikoDelarich** [Part-DB/Part-DB-server#701]
**Describe the bug**
The search window and the search options window don't disappear automatically when losing focus.

**To Reproduce**
1. Click "Search options" -> Search options are displayed
2. Click anywhere else -> Still displayed
3. Click inside the search field -> Search window opens up (on top of search options)
4. Click anywhere else -> Still visible

**Expected behavior**
The search window and the search options window should be automatically hidden on focus loss.

**Screenshots**
![image](https://github.com/user-attachments/assets/3364b751-bb1b-423b-b114-f8a051a913bc)

**Server Side**
- Part-DB Version: 1.14.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox
 - Version: Latest

**Comment by jbtronics** [comment]
The problem with the search field was caused by some limitation of the autocomplete library, which do not support multiple instances. The problem only occured, when you started with the homepage (where a second search field is located). When you started at any other page, the search field in the navbar properly closes when loosing focus.

I added some custom code for defocus handling as a workaround, and with the latest commits it now should work fine.
